apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: with-baby-store-mongo
spec:
  selector:
    matchLabels:
      app: with-baby-store-mongo
  serviceName: with-baby-store-mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: with-baby-store-mongo
    spec:
      containers:
      - name: with-baby-store-mongo
        image: mongo:latest
        args: ["--bind_ip_all", "--replSet=rs0"]
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: data
          mountPath: /data/db

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: with-baby-store-mongo
      resources:
        requests:
          storage: 1Gi
