apiVersion: v1
kind: Service
metadata:
  name: with-baby-store-mongo
  labels: 
    group: with-baby-store
spec:
  selector:
    app: with-baby-store-mongo
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: with-baby-store
  labels: 
    group: with-baby-store
spec:
  selector:
    app: with-baby-store
  ports:
  - port: 8000
    targetPort: 8000
    name: web
  clusterIP: None